### PR TITLE
move project to native esm module

### LINKED ISSUE #65: failed to import "svelte-intl-precompile"
```
11:16:24 a.m. [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "svelte-intl-precompile"
|- Error [ERR_REQUIRE_ESM]: require() of ES Module /home/marcgodard/Documents/Github/swp-web/node_modules/svelte/src/runtime/store/index.js from /home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/stores/dictionary.js not supported.
Instead change the require of index.js in /home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/stores/dictionary.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/stores/dictionary.js:5:17)
    at Object.<anonymous> (/home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/includes/loaderQueue.js:4:22)
    at Object.<anonymous> (/home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/index.js:18:23)
    at async Promise.all (index 0)
    at async nodeImport (file:///home/marcgodard/Documents/Github/swp-web/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55947:17)
    at async ssrImport (file:///home/marcgodard/Documents/Github/swp-web/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55840:24)
    at async eval (/home/marcgodard/Documents/Github/swp-web/src/routes/+page.svelte:4:31)
    at async instantiateModule (file:///home/marcgodard/Documents/Github/swp-web/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55902:9)
```

### PR DESCRIPTION
**Pull request by tobiaskohlbau**
Build as native ESM module and only provide commonjs as a fallback for legacy node versions. Typescript unfortunetly does not support compiling to import versions with file extension. The project itself suggests to add the js extension within the typescript files itself. This neither does look right nor feelds right, but they do not provide another solution.

See https://www.typescriptlang.org/docs/handbook/esm-node.html for more information.

> When a .ts file is compiled as an ES module, ECMAScript import/export syntax is left alone in the .js output; when it’s compiled as a CommonJS [module](https://www.typescriptlang.org/tsconfig#module), it will produce the same output you get today under module: commonjs.
>
>This also means paths resolve differently between .ts files that are ES modules and ones that are CJS modules. For example, let’s say you have the following code today:

Fixes cibernox/svelte-intl-precompile#65

**Please note that I'm not very familiar with the Node/JS ecosystem, please let me know if the PR needs to be adjusted in order to align with the maintainers or other best practices.**

### CODE REVIEW

**Comment by stalkerg** [comment]
You shouldn't change `.ts` files, you should just change tsconfig.

**Comment by tobiaskohlbau** [comment]
> You shouldn't change `.ts` files, you should just change tsconfig.

Did you read the reference I posted? The changes in the TypeScript files are needed. NodeJS aligns with the browser ESM specification of requiring file extensions during the import statements. TypeScript does not provide a way to compile into files with file extension, therefore they suggest using the file extension within TypeScript itself. It's sure ugly as hell, but there is no other option.

**Comment by stalkerg** [comment]
@tobiaskohlbau it should be generated by TS compiler.

**Comment by stalkerg** [comment]
sorry, I read https://www.typescriptlang.org/docs/handbook/esm-node.html again, and you're right. It's very confusing from TS point of view. 

> This might feel a bit cumbersome at first

yeah.

**Comment by tobiaskohlbau** [comment]
No worries, I did not believe it either on my first read. It feels so cumbersome to have the _.js_ Extension within the TypeScript files itself. I can't find a possible reason why the TS Authors think this is a viable solution instead of an option to add the extension on compilation.

**Comment by cibernox** [comment]
I'm going to merge this and release as a prerelease first.

Thanks for this!

**Comment by cibernox** [comment]
I tried the beta packages in a brand new sveltekit app with svelte 4 and this worked!!

**Comment by tobiaskohlbau** [comment]
Thanks for merging and the fast response to get this resolved. Helps a lot for downstream projects :)

**Pull request merged**
