### PR TITLE
Add a JSON accessor, to get a segment of raw JSON from dictionary

### PR DESCRIPTION
**Pull request by brev**
Add a `$json('key')` accessor, to get a segment of raw JSON from dictionary.

With a new passing test.

Thanks, I hope your vacation is great. :)

### CODE REVIEW

**Comment by cibernox** [comment]
What's the rationale behind this feature? In what scenario is this useful?

**Comment by brev** [comment]
@cibernox Rationale:

From within my `.svelte` files, I call out to plain JS modules to handle JSON-LD Schema.org structured data generation, and a few other similar things, which require some of my locale strings.  Using `json()`, I can just pass them nicely.  Otherwise, I'd have to manually load locales, strings, etc, from those modules separately (which I'm not even sure how to do intelligently).

Also, matches a missing feature of `svelte-i18n`.

thanks.

**Comment by cibernox** [comment]
I see. Probably that feature was added after I forked  svelte-i18n API. If you can fix the merge conflict I'll merge it. Don't worry about the CI failures, I'll take care of those.

**Comment by brev** [comment]
Fixed merge conflict, thanks!

**Comment by cibernox** [comment]
There is still a legitimate test error:

```
  ● json › retrieves json segment of messages on the current locale

    TypeError: Cannot read property 'subscribe' of undefined
```

**Comment by brev** [comment]
The test passes after I run `npm run build`, and have a few updated files in my `dist/` folder. But `.gitignore` contains `dist`, what do you think?

**Comment by cibernox** [comment]
I thought I had built it before testing but clearly I didn't. My bad. Merged!

**Comment by cibernox** [comment]
Published 0.4.6 🎉

**Pull request merged**
